<?php if(Mage::getStoreConfig('blog/menu/show_recent_post')):?>
<div class="block em_block-recent-post box">
    <div class="block-title">
        <strong><span><?php echo $this->__('Recent Posts'); ?></span></strong>
    </div>
    <div class="block-content">
    	<?php if (count($this->getRecentPost())>0):?>
        <ol>
            <?php $i =0; foreach ($this->getRecentPost() as $p): ?>
                <li class="item <?php echo (($i==3)||($i+1==count($this->getRecentPost())))? 'last': ''?>">
                    <a class="post-title" href="<?php echo $p->getPostUrl();?>" ><?php echo $p->getTitle();?></a>
                    <?php $date = new DateTime($p->getCreatedAt());?>
                    <small class="time-stamp"><?php echo $date->format('l, M j Y, h:iA'); ?></small>
                    <span class="post-by"><?php echo $this->__('Posted by').' '?><span><?php echo $p->getAuthor()->getUsername()?></span></span>
                </li>
             <?php $i++; if ($i ==4) break;?>
            <?php endforeach; ?>
        </ol>
        <?php else:?>
        	<p class="empty"><?php echo $this->__('No recent post') ?></p>
        <?php endif;?>
    </div>
</div>
<?php endif;?>