<?php
    /* get config from themesetting */

$setting = Mage::helper('em0075settings');
$fonts = Mage::getModel('em0075settings/config_font')->toOptionArray();
$boxwide = Mage::getModel('em0075settings/config_boxwide')->toOptionArray();
?>
<a href="javascript:void(0)" class="btn-toggle">+ open/close</a>
<div id="demotool_variation" class="hide-lte0">
	
	
	<div class="variation-cp" style="display:none">
		<div class="demotool-title">Magento Theme Variations</div>
		<form method="GET" name="emvariationform" id="emvariationform" action="<?php echo $this->getSkinUrl('css/theme.css.php') ?>">
		<div class="demotool-content">
            <!-- Google Fonts -->
			<div class="demo demo-02">
				<div class="content-title"><span>Google Fonts</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">Import these google fonts</div>
									<div class="input">
										<select id="em_variation_google_font" multiple="true" rows="10" size="10">
											<?php $selectedFonts = explode(',', $setting->getTypography_GoogleFonts()) ?>
											<?php foreach ($fonts as $_font): ?>
											<option value="<?php echo htmlspecialchars($_font['value']) ?>" <?php echo @in_array($_font['value'], $selectedFonts) ? 'selected="selected"' : '' ?>><?php echo $_font['label'] ?></option>
											<?php endforeach ?>
										</select>
									</div>
									<div class="desc">Select which google fonts should be imported to your site</div>
								</div>
							</div>
						</div>
					</div>
				</div>					
			</div>
			
			<!-- Element Fonts -->
			<div class="demo demo-03">
				<div class="content-title"><span>Element Fonts</span></div>
				
				<div class="wrapper-content">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">General Font</div>
									<div class="input"><input type="text" name="general_font" value="<?php echo htmlspecialchars($setting->getTypography_GeneralFont()) ?>" class="input-text"/></div>
									<div class="desc">Font for body, content, text...<br/>E.g. <em>12px/1.35 Arial, Helvetica, sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H1</div>
									<div class="input"><input type="text" name="h1_font" value="<?php echo htmlspecialchars($setting->getTypography_H1Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 22px/1.15 helvetica,arial,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H2</div>
									<div class="input"><input type="text" name="h2_font" value="<?php echo htmlspecialchars($setting->getTypography_H2Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. normal <em>normal 20px/1.25 helvetica,arial,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H3</div>
									<div class="input"><input type="text" name="h3_font" value="<?php echo htmlspecialchars($setting->getTypography_H3Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 18px/1.25 helvetica,arial,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H4</div>
									<div class="input"><input type="text" name="h4_font" value="<?php echo htmlspecialchars($setting->getTypography_H4Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 16px/1.35 helvetica,arial,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H5</div>
									<div class="input"><input type="text" name="h5_font" value="<?php echo htmlspecialchars($setting->getTypography_H5Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 14px/1.35 helvetica,arial,sans-serif</em></div>
								</div>
                                <div class="row">
                                    <div class="label">H6</div>
                                    <div class="input"><input type="text" name="h6_font" value="<?php echo htmlspecialchars($setting->getTypography_H6Font()) ?>" class="input-text" /></div>
                                    <div class="desc">E.g. <em>normal 12px/1.35 helvetica,arial,sans-serif</em></div>
                                </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		
			<!-- Element Fonts -->
			<div class="demo demo-03">
				<div class="content-title"><span>General</span></div>
				
				<div class="wrapper-content">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">Box Shadow</div>
									<div class="input"><input type="text" name="box_shadow" value="<?php echo htmlspecialchars($setting->getTypography_BoxShadow()) ?>" class="input-text"/></div>
									<div class="desc">E.g. <em style="box-shadow:6px 0px 14px #ededed inset">6px 0px 14px #ededed inset</em></div>
								</div>
								<div class="row">
									<div class="label">Border Radius</div>
									<div class="input"><input type="text" name="rounded_corner" value="<?php echo htmlspecialchars($setting->getTypography_RoundedCorner()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>4px</em></div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
			
			<!-- General -->
			<div class="demo demo-02">
				<div class="content-title"><span>Choose Your Layout Style</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">Box/Wide Mode</div>
									<div class="input">
                                        <select id="em_box_wide" name="em_box_wide" class="em_box_wide select">
                                            <?php $selectedBoxWide = explode(',', $setting->getGeneral_BoxWide()) ?>
                                            <?php foreach ($boxwide as $boxwide_item): ?>
											     <option value="<?php echo htmlspecialchars($boxwide_item['value']) ?>" <?php echo @in_array($boxwide_item['value'], $selectedBoxWide) ? 'selected="selected"' : '' ?>><?php echo $boxwide_item['label'] ?></option>
											<?php endforeach ?>
                                        </select>
									</div>
									<div class="desc">Default: Wide</div>
								</div>
                                
                                <div id="option-mode">
                                    <div class="row">
    									<div class="label">Page Background Color</div>
    									<div class="input"><input type="text" name="page_bgcolor" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgcolor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default #000000</div>
    								</div>
                                    
                                    <div class="row">
    									<div class="label">Page Background Pattern</div>
    									<div class="input">
    										<input type="hidden" name="page_bgimage" value="<?php echo 'url(../images/stripes/'.htmlspecialchars($setting->getGeneral_PageBgimage()).')'; ?>"  />
    										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0075/images/stripes/'; ?>
    										<?php foreach (Mage::getModel('em0075settings/config_stripes')->toOptionArray() as $row):?>
    										<a href="#" class="page_bgimage" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" <?php echo $setting->getGeneral_PageBgimage() == $row['value'] ? 'selected="selected"' : '' ?>>
    											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
    										</a>
    										<?php endforeach ?>
    									</div>
    									<div class="desc">Specify background pattern image.</div>
    								</div>
                                    <div class="row">
    									<div class="label">Page Background Position</div>
    									<div class="input"><input type="text" name="page_bgposition" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgposition()) ?>" class="input-text"/></div>
    									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
    								</div>
                                    <div class="row">
    									<div class="label">Page Background Repeat</div>
    									<div class="input"><input type="text" name="page_bgrepeat" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgrepeat()) ?>" class="input-text"/></div>
    									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
    								</div>
                                </div>
							</div>
						</div>
					</div>
				</div>					
			</div>
			
            <!-- Top Header -->
            <div class="demo demo-01">
                <div class="content-title"><span>Top Header</span></div>
                <div class="wrapper-content general-setting">
                    <div class="box last">
                        <div class="content">
                            <div class="col col-2">
                                <div class="row">
                                    <div class="label">Top Header Background Color</div>
                                    <div class="input"><input type="text" name="top_header_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_TopHeaderBgcolor()) ?>" class="color-picker" /></div>
                                    <div class="desc">Default: #0a8df3</div>
                                </div>

                                <div class="row">
                                    <div class="label">Header Text Color</div>
                                    <div class="input"><input type="text" name="top_header_text_color" value="<?php echo htmlspecialchars($setting->getTypography_TopHeaderTextColor()) ?>" class="color-picker" /></div>
                                    <div class="desc">Text color used in top header</div>
                                </div>
                            </div>
                            <div class="col col-2">
                                <div class="row">
                                    <div class="label">Top Header Background Color 2</div>
                                    <div class="input"><input type="text" name="top_header2_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_TopHeader2Bgcolor()) ?>" class="color-picker" /></div>
                                    <div class="desc">Default: #0564c6</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

			<!-- Header -->
			<div class="demo demo-01">
				<div class="content-title"><span>Header</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-2">
                                <div class="row">
									<div class="label">Header Background Color</div>
									<div class="input"><input type="text" name="header_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgcolor()) ?>" class="color-picker" /></div>
									<div class="desc">Background color used in header <br/> Default:#003e6d</div>
								</div>

                                <div class="row">
                                    <div class="label">Header Background Color 3</div>
                                    <div class="input"><input type="text" name="header_bgcolor3" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgcolor3()) ?>" class="color-picker" /></div>
                                    <div class="desc">Used in cart header background <br/> Default:#0282e2</div>
                                </div>
                                
                                <div class="row">
									<div class="label">Header Background Position</div>
									<div class="input"><input type="text" name="header_bgposition" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgposition()) ?>" class="input-text" /></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit</div>
								</div>
			
								 <div class="row">
                                    <div class="label">Header Text Color</div>
                                    <div class="input"><input type="text" name="header_text_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderTextColor()) ?>" class="color-picker" /></div>
                                    <div class="desc">Default:#ffffff</div>
                                </div>

                                <div class="row">
                                    <div class="label">Header Line Color</div>
                                    <div class="input"><input type="text" name="header_line" value="<?php echo htmlspecialchars($setting->getTypography_HeaderLine()) ?>" class="color-picker" /></div>
                                    <div class="desc">Line color used in header</div>
                                </div>
                                
                                <div class="row">
                                    <div class="label">Header Line 3 Color</div>
                                    <div class="input"><input type="text" name="header3_line" value="<?php echo htmlspecialchars($setting->getTypography_Header3Line()) ?>" class="color-picker" /></div>
                                    <div class="desc">used in cart header line</div>
                                </div>
							</div>
							<div class="col col-2">
                                <div class="row">
                                    <div class="label">Header Background Color 2</div>
                                    <div class="input"><input type="text" name="header_bgcolor2" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgcolor2()) ?>" class="color-picker" /></div>
                                    <div class="desc">Background color 2 used in header <br/> Default:#0a8ff3</div>
                                </div>
                                
                                <div class="row">
                                    <div class="label">Header Background Color 4</div>
                                    <div class="input"><input type="text" name="header_bgcolor4" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgcolor4()) ?>" class="color-picker" /></div>
                                    <div class="desc">Used in search,input header <br/> Default:#fff</div>
                                </div>

								<div class="row">
									<div class="label">Header Background Repeat</div>
									<div class="input"><input type="text" name="header_bgrepeat" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgrepeat()) ?>" class="input-text" /></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit</div>
								</div>

                                <div class="row">
                                    <div class="label">Header Text Color 2</div>
                                    <div class="input"><input type="text" name="header_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText2Color()) ?>" class="color-picker" /></div>
                                    <div class="desc">Default:#797979</div>
                                </div>

                               <div class="row">
                                    <div class="label">Header Line 2 Color</div>
                                    <div class="input"><input type="text" name="header2_line" value="<?php echo htmlspecialchars($setting->getTypography_Header2Line()) ?>" class="color-picker" /></div>
                                    <div class="desc">Used in cart header line</div>
                                </div>
                                
							</div>
							<div class="col">
                               
                                 <div class="row">
									<div class="label">Header Background Pattern</div>
									<div class="input">
										<input type="hidden" name="header_bgimage" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgimage()) ?>"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0075/images/stripes/'; ?>
										<?php foreach (Mage::getModel('em0075settings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="header_bgimage" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" <?php echo $setting->getTypography_HeaderBgimage() == $row['value'] ? 'selected="selected"' : '' ?>>
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Top Menu -->
			<div class="demo demo-01">
				<div class="content-title"><span>Top Menu</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-2">
                                <div class="row">
									<div class="label">Top Menu Background Color</div>
									<div class="input"><input type="text" name="menu_top_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_MenuTopBgcolor()) ?>" class="color-picker" /></div>
									<div class="desc">Background of Top Menu</div>
								</div>
                                <div class="row">
									<div class="label">Top Menu Text Color</div>
									<div class="input"><input type="text" name="menu_top_text_color" value="<?php echo htmlspecialchars($setting->getTypography_MenuTopTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Text color used in Top Menu</div>
								</div>
								 <div class="row">
									<div class="label">Menu Line</div>
									<div class="input"><input type="text" name="menu_line" value="<?php echo htmlspecialchars($setting->getTypography_MenuLine()) ?>" class="color-picker"/></div>
									<div class="desc">Line color used in Menu</div>
								</div>
							</div>
							<div class="col col-2">
                          		<div class="row">
									<div class="label">Top Menu Hover/Active Background Color</div>
									<div class="input"><input type="text" name="menu_top_hover_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_MenuTopHoverBgcolor()) ?>" class="color-picker" /></div>
									<div class="desc">Background of Top Menu when hover</div>
								</div>
                                
                                <div class="row">
									<div class="label">Top Menu Text Hover/Active Color</div>
									<div class="input"><input type="text" name="menu_active_text_color" value="<?php echo htmlspecialchars($setting->getTypography_MenuActiveTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Text color used in Top Menu wher hover</div>
								</div>   
							</div>        
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Dropdown Menu -->
			<div class="demo demo-01">
				<div class="content-title"><span>Dropdown Menu</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-2">
                                <div class="row">
									<div class="label">Dropdown Menu Background Color</div>
									<div class="input"><input type="text" name="menu_drop_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_MenuDropBgcolor()) ?>" class="color-picker" /></div>
									<div class="desc">Background color used in Dropdown Menu</div>
								</div>
								<div class="row">
									<div class="label">Dropdown Menu Text Color</div>
									<div class="input"><input type="text" name="menu_drop_text_color" value="<?php echo htmlspecialchars($setting->getTypography_MenuDropTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default:#686868</div>
								</div>
                                <div class="row">
                                    <div class="label">Dropdown Menu Hover/Active Text Color</div>
                                    <div class="input"><input type="text" name="menu_drop_link_color" value="<?php echo htmlspecialchars($setting->getTypography_MenuDropLinkColor()) ?>" class="color-picker" /></div>
                                    <div class="desc">Text color used in hover Dropdown Menu</div>
                                </div>
							</div>
							<div class="col col-2">
								<div class="row">
									<div class="label">Dropdown Menu Hover/Active Background Color</div>
									<div class="input"><input type="text" name="menu_drop_hover_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_MenuDropHoverBgcolor()) ?>" class="color-picker" /></div>
									<div class="desc">Background color used in Dropdown Menu when hover</div>
								</div>
                                <div class="row">
                                    <div class="label">Dropdown Menu Text Color 2</div>
                                    <div class="input"><input type="text" name="menu_drop_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_MenuDropText2Color()) ?>" class="color-picker" /></div>
                                    <div class="desc">Default:#131313</div>
                                </div>
                                <div class="row">
                                    <div class="label">Menu Drop Line</div>
                                    <div class="input"><input type="text" name="menu_drop_line" value="<?php echo htmlspecialchars($setting->getTypography_MenuDropLine()) ?>" class="color-picker"/></div>
                                    <div class="desc">Line color used in Dropdown Menu</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Body -->
			<div class="demo demo-01">
				<div class="content-title"><span>Body</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-2 first">
                                <div class="row">
									<div class="label">Body Background Color</div>
									<div class="input"><input type="text" name="body_bgcolor1" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgcolor1()) ?>" class="color-picker" /></div>
									<div class="desc">Background color 1st used in body <br/> Default:#ffffff</div>
								</div>
                                
                                <div class="row">
									<div class="label">3th Body Background Color</div>
									<div class="input"><input type="text" name="body_bgcolor3" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgcolor3()) ?>" class="color-picker" /></div>
									<div class="desc">Used in right title home background <br/>Default:#69a204</div>
								</div>

                                <div class="row">
                                    <div class="label">5th Body Background Color</div>
                                    <div class="input"><input type="text" name="body_bgcolor5" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgcolor5()) ?>" class="color-picker" /></div>
                                    <div class="desc">Used in title checkout background <br/> Default:#171313</div>
                                </div>

								<div class="row">
									<div class="label">Body Background Repeat</div>
									<div class="input"><input type="text" name="body_bgrepeat" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgrepeat()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit</div>
								</div>
                            </div>
                            
                            <div class="col col-2">
                                <div class="row">
									<div class="label">2nd Body Background Color</div>
									<div class="input"><input type="text" name="body_bgcolor2" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgcolor2()) ?>" class="color-picker" /></div>
									<div class="desc">Used in page title, block title...<br/>Default:#f1f1f1</div>
								</div>
                                <div class="row">
                                    <div class="label">4th Body Background Color</div>
                                    <div class="input"><input type="text" name="body_bgcolor4" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgcolor4()) ?>" class="color-picker" /></div>
                                    <div class="desc">Used in label background <br/>Default:#f40000</div>
                                </div>
                                <div class="row">
									<div class="label">Body Background Position</div>
									<div class="input"><input type="text" name="body_bgposition" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgposition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit</div>
								</div>
							</div>
                                
                            <div class="col">
                            	<div class="row">
									<div class="label">Body Background Pattern</div>
									<div class="input">
										<input type="hidden" name="body_bgimage" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgimage()) ?>"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0075/images/stripes/'; ?>
										<?php foreach (Mage::getModel('em0075settings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="body_bgimage" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" <?php echo $setting->getTypography_BodyBgimage() == $row['value'] ? 'selected="selected"' : '' ?>>
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
                            </div>
                            <div class="col col-2 first">
                            	<div class="row">
									<div class="label">Body Text 1st Color</div>
									<div class="input"><input type="text" name="body_text_color1" value="<?php echo htmlspecialchars($setting->getTypography_BodyTextColor1()) ?>" class="color-picker" /></div>
									<div class="desc">Used in tab title home,breadcrumbs, page title...<br/>Default:#5d5d5d</div>
								</div>
								<div class="row">
									<div class="label">Body Text 3th Color</div>
									<div class="input"><input type="text" name="body_text_color3" value="<?php echo htmlspecialchars($setting->getTypography_BodyTextColor3()) ?>" class="color-picker" /></div>
									<div class="desc">Used in table, checkout title...<br/>Default:#7f7f7f</div>
								</div>
                                <div class="row">
                                    <div class="label">Body Text 5th Color</div>
                                    <div class="input"><input type="text" name="body_text_color5" value="<?php echo htmlspecialchars($setting->getTypography_BodyTextColor5()) ?>" class="color-picker" /></div>
                                    <div class="desc">Used in title block text...<br/>Default:#ff7200</div>
                                </div>
								<div class="row">
									<div class="label">Body Link Color</div>
									<div class="input"><input type="text" name="body_link_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyLinkColor()) ?>" class="color-picker" /></div>
									<div class="desc">Link color used in Body <br/>Default:#131313</div>
								</div>
								<div class="row">
									<div class="label">Body Line 2</div>
									<div class="input"><input type="text" name="body_line2" value="<?php echo htmlspecialchars($setting->getTypography_BodyLine2()) ?>" class="color-picker" /></div>
									<div class="desc">Border's color in category</div>
								</div>
                            </div>
                            <div class="col col-2">
                            	<div class="row">
									<div class="label">Body Text 2nd Color</div>
									<div class="input"><input type="text" name="body_text_color2" value="<?php echo htmlspecialchars($setting->getTypography_BodyTextColor2()) ?>" class="color-picker" /></div>
									<div class="desc">Used in my account, product name hover...<br/>Default:#008bf4</div>
								</div>
								<div class="row">
									<div class="label">Body Text 4th Color</div>
									<div class="input"><input type="text" name="body_text_color4" value="<?php echo htmlspecialchars($setting->getTypography_BodyTextColor4()) ?>" class="color-picker" /></div>
									<div class="desc">Used in required text<br/>Default:#ff0000</div>
								</div>
                                <div class="row">
                                    <div class="label">Body Text 6th Color</div>
                                    <div class="input"><input type="text" name="body_text_color6" value="<?php echo htmlspecialchars($setting->getTypography_BodyTextColor6()) ?>" class="color-picker" /></div>
                                    <div class="desc">Used in toolbar, title checkout<br/>Default:#ffffff</div>
                                </div>
								 <div class="row">
									<div class="label">Body Line 1</div>
									<div class="input"><input type="text" name="body_line1" value="<?php echo htmlspecialchars($setting->getTypography_BodyLine1()) ?>" class="color-picker" /></div>
									<div class="desc">Border's color in input, col left, col right..</div>
								</div>
								<div class="row">
									<div class="label">Body Line 3</div>
									<div class="input"><input type="text" name="body_line3" value="<?php echo htmlspecialchars($setting->getTypography_BodyLine3()) ?>" class="color-picker" /></div>
									<div class="desc">Border's color of hover image in shop by</div>
								</div>
								<input type="hidden" name="additional_css_file" value="<?php echo htmlspecialchars($setting->getTypography_AdditionalCssFile()) ?>" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Footer -->
			<div class="demo demo-01">
				<div class="content-title"><span>Footer</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-2 first">
                                <div class="row">
									<div class="label">Footer Background Color</div>
									<div class="input"><input type="text" name="footer_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgcolor()) ?>" class="color-picker" /></div>
									<div class="desc">Used in newsletter<br/>Default:#171313</div>
								</div>
                                <div class="row">
									<div class="label">Footer Background Position</div>
									<div class="input"><input type="text" name="footer_bgposition" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgposition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit</div>
								</div>
                                <div class="row">
                                    <div class="label">Footer Text Color 1</div>
                                    <div class="input"><input type="text" name="footer_text_color1" value="<?php echo htmlspecialchars($setting->getTypography_FooterTextColor1()) ?>" class="color-picker" /></div>
                                    <div class="desc">Default:#5d5d5d</div>
                                </div>
                                <div class="row">
                                    <div class="label">Footer Text Color 3</div>
                                    <div class="input"><input type="text" name="footer_text_color3" value="<?php echo htmlspecialchars($setting->getTypography_FooterTextColor3()) ?>" class="color-picker" /></div>
                                    <div class="desc">Default:#008beb</div>
                                </div>
                            </div>
                            
                            <div class="col col-2">
                                <div class="row">
                                    <div class="label">Footer Background Color 2</div>
                                    <div class="input"><input type="text" name="footer_bgcolor1" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgcolor1()) ?>" class="color-picker" /></div>
                                    <div class="desc">Background color 2 used in Footer<br/>Default:#f4f4f4</div>
                                </div>
                                <div class="row">
                                    <div class="label">Footer Background Repeat</div>
                                    <div class="input"><input type="text" name="footer_bgrepeat" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgrepeat()) ?>" class="input-text"/></div>
                                    <div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit</div>
                                </div>
                                <div class="row">
                                    <div class="label">Footer Text Color 2</div>
                                    <div class="input"><input type="text" name="footer_text_color2" value="<?php echo htmlspecialchars($setting->getTypography_FooterTextColor2()) ?>" class="color-picker" /></div>
                                    <div class="desc">Default:#ffffff</div>
                                </div>
                                <div class="row">
                                    <div class="label">Footer Line Color</div>
                                    <div class="input"><input type="text" name="footer_line1" value="<?php echo htmlspecialchars($setting->getTypography_FooterLine1()) ?>" class="color-picker" /></div>
                                    <div class="desc">Line color used in Footer </div>
                                </div>
                            </div>
                            
                            <div class="col">
                                <div class="row">
									<div class="label">Footer Background Pattern</div>
									<div class="input">
										<input type="hidden" name="footer_bgimage" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgimage()) ?>"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0075/images/stripes/'; ?>
										<?php foreach (Mage::getModel('em0075settings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="footer_bgimage" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" <?php echo $setting->getTypography_FooterBgimage() == $row['value'] ? 'selected="selected"' : '' ?>>
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

			<!-- 1st Buttons -->
			<div class="demo demo-01">
				<div class="content-title"><span>1st Button Default</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">1st Button Background Color</div>
									<div class="input"><input type="text" name="button1_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_Button1Bgcolor()) ?>" class="color-picker" /></div>
									<div class="desc">Background color used in button 1st</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">1st Button Text Color</div>
									<div class="input"><input type="text" name="button1_color" value="<?php echo htmlspecialchars($setting->getTypography_Button1Color()) ?>" class="color-picker" /></div>
									<div class="desc">Color text used in btton 1st</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
			
            <!-- 2nd Buttons -->
			<div class="demo demo-01">
				<div class="content-title"><span>2nd Button( wishlist/compare detail page)</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Background Color</div>
									<div class="input"><input type="text" name="button2_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_Button2Bgcolor()) ?>" class="color-picker" /></div>
									<div class="desc">Background color used in button 2nd</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Line Color</div>
									<div class="input"><input type="text" name="button2_line" value="<?php echo htmlspecialchars($setting->getTypography_Button2Line()) ?>" class="color-picker" /></div>
									<div class="desc">Line color used in button 2nd</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Text Color</div>
									<div class="input"><input type="text" name="button2_color" value="<?php echo htmlspecialchars($setting->getTypography_Button2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Color text used in btton 2nd</div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- 3th Buttons -->
            <div class="demo demo-01">
                <div class="content-title"><span>3th Button(checkout button)</span></div>
                <div class="wrapper-content general-setting">
                    <div class="box last">
                        <div class="content">
                            <div class="col col-1">
                                <div class="row">
                                    <div class="label">3th Button Background Color</div>
                                    <div class="input"><input type="text" name="button3_bgcolor" value="<?php echo htmlspecialchars($setting->getTypography_Button3Bgcolor()) ?>" class="color-picker" /></div>
                                    <div class="desc">Background color used in button 3th</div>
                                </div>
                            </div>

                            <div class="col col-1">
                                <div class="row">
                                    <div class="label">3th Button Text Color</div>
                                    <div class="input"><input type="text" name="button3_color" value="<?php echo htmlspecialchars($setting->getTypography_Button3Color()) ?>" class="color-picker" /></div>
                                    <div class="desc">Color text used in btton 3th</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

			<a href="#" class="btn-reset">Reset</a>
			<a href="#" class="btn-apply">Apply Changes</a>
		</div>
		<div class="copyright">Theme designed by <a href="http://emthemes.com/premium-magento-themes.html" title="Premium Magento Themes &amp; Premium Magento Templates" target="_blank">EMThemes.com</a></div>
		</form>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
jQuery(function($) {
	var panel = $('#demotool_variation').css({'left':'-100%', 'position':'absolute'});
	
	$('a.btn-toggle').click(function () {
		if (!panel.hasClass('show')) {
			$('.variation-cp').show();
			panel.css('top', Math.max($(document).scrollTop(), Math.min($(this).offset().top, $(document).scrollTop() + $(window).height() - panel.outerHeight())) + 'px')
				.addClass('show')
				.animate({'left':$(this).width() + 1 + 'px'});
		} else {
			panel.removeClass('show')
				.animate({'left':-$(this).width() - panel.outerWidth() - 10 + 'px'}, 
				500, function () {
					$('.variation-cp').hide();
				});
			
		}
		return false;
	});

	// toogle section content-title
	$('#demotool_variation .content-title').click(function() {
		$(this).next('.wrapper-content').slideToggle('fast');
	}).trigger('click').first().trigger('click');
	

	// toggle box content
	$('#demotool_variation .box .title').click(function () {
		var box = $(this).parent();

		if (box.children('.content').is(':visible')) {
			box.children('.content').slideUp('fast');
			box.addClass('close');
		} else {
			box.children('.content').slideDown('fast');
			box.removeClass('close');
		}
			
	});
	
	
	var oldCss = $('#emcssvariation').attr('href');
	
	$('#demotool_variation .btn-apply').click(function() {
		$('#emcssvariation').attr('href', $('#emvariationform').attr('action') + '?' + $('#emvariationform').serialize());
		// box/wide mode
        var mode = $('#em_box_wide').val();
        if(mode == 'box'){
            $('.wrapper').addClass('em-box-custom');
        }else{
            $('.wrapper').removeClass('em-box-custom');         
        }
		return false;
	});
	
	$('#demotool_variation .btn-reset').click(function() {
		$('#emcssvariation').attr('href', oldCss);
		$('#demotool_variation input[type=text], #demotool_variation select, #demotool_variation input[type=hidden]').val('').css('background-color', '');
		if($('.wrapper').hasClass('em-box-custom')){
            $('.wrapper').removeClass('em-box-custom');
        }
		return false;
	});


	// load google fonts
	var fontLoaded = {};
	$('#em_variation_google_font').after('<p id="em_variation_google_font_preview" style="font-size:20px;padding:10px 0"></p>')
		.bind('change', function() {
			var font = $(this).val();
			if (font.length > 0) {
				font = font[font.length-1];
				if (typeof fontLoaded[font] == 'undefined') {
					$('head').append('<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family='+encodeURIComponent(font)+':400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic&subset=latin,cyrillic-ext,cyrillic,greek-ext,greek,vietnamese,latin-ext"></link>');
					$('#em_variation_google_font_preview').html(font)
						.css('font-family', font);
				}
			}
		});
		
	// stripes pattern
    $('#demotool_variation a.t_header_bgimage').click(function() {
        $('#demotool_variation a.t_header_bgimage').removeClass('selected');
        $(this).addClass('selected');
        $('#demotool_variation input[name=t_header_bgimage]').val('url(../images/stripes/' + $(this).data('input-value') + ')');
        return false;
    });

	$('#demotool_variation a.header_bgimage').click(function() {
		$('#demotool_variation a.header_bgimage').removeClass('selected');
		$(this).addClass('selected');
		$('#demotool_variation input[name=header_bgimage]').val('url(../images/stripes/' + $(this).data('input-value') + ')');
		return false;
	});

	$('#demotool_variation a.body_bgimage').click(function() {
		$('#demotool_variation a.body_bgimage').removeClass('selected');
		$(this).addClass('selected');
		$('#demotool_variation input[name=body_bgimage]').val('url(../images/stripes/' + $(this).data('input-value') + ')');
		return false;
	});

	$('#demotool_variation a.footer_bgimage').click(function() {
		$('#demotool_variation a.footer_bgimage').removeClass('selected');
		$(this).addClass('selected');
		$('#demotool_variation input[name=footer_bgimage]').val('url(../images/stripes/' + $(this).data('input-value') + ')');
		return false;
	});
	$('#demotool_variation a.page_bgimage').click(function() {
		$('#demotool_variation a.page_bgimage').removeClass('selected');
		$(this).addClass('selected');
		$('#demotool_variation input[name=page_bgimage]').val('url(../images/stripes/' + $(this).data('input-value') + ')');
		return false;
	});
	$('#em_box_wide').change(function(){
        var modevalue = $('#em_box_wide').val();
        if(modevalue == 'box'){
            $('#option-mode').show();
        }else{
            $('#option-mode').hide();       
        }
    });
    
    $(document).ready(function(){
        var b = $('#em_box_wide').val();
        if(b=='wide'){
            $('#option-mode').hide();
        }else{
            $('#option-mode').show();
        }
        
    }); 
});
//]]>
</script>