<?php if(Mage::getStoreConfig('blog/menu/show_recent_comment')):?>
<div class="block em_block-recent-comments box">
    <div class="block-title">
        <strong><span><?php echo $this->__('Recent Comments')?></span></strong>
    </div>
	<div class="block-content">
		<ol type="square">
			<?php $rcs = $this->getCommentCollection(); $i = 0;?>
			<?php if($rcs->count() > 0 ) : ?>
				<?php $i=0; foreach($rcs as $rc): ?>
      				<?php if($i == 0)
      					$class="first";
      					else
      					$class='';
      				?>
      				<?php if(($i==3)||($i+1==count($this->getCommentCollection())))
      					$class2="last";
      					else 
      					$class2="";
      				?>
      					<li class="item recent-comment-item <?php echo $class;?> <?php echo $class2 ?>">
						   <a class="comment-title" href="<?php echo $rc->getPost()->getPostUrl();?>" ><?php echo $rc->getTitlePost();?></a>
						   <?php $date = new DateTime($rc->getTime());?>
						   <small class="time-stamp"><?php echo $date->format('l, M j Y, h:iA'); ?></small>
      					   <div class="recent-comment-content">
      					       <?php echo $this->getTitleComment($rc->getCommentContent(),50); ?>
      					   </div>
						   <span class="comment-by"><?php echo $this->__('Commented by').' '?>
							   <span><?php echo $rc->getUsername()?></span>
						   </span>
      					</li>
      			<?php $i++; if($i==4) break;?>
			    <?php endforeach;?>						
			<?php else :  ?>
				<li><p class="empty"><?php echo $this->__('No recent comment') ?></p></li>
				<?php $i++;?>
			<?php endif; ?>	
		</ol>
	</div>
</div>
<?php endif;?>